export const NameList: string[] = [
  'Ana Amari',
  'Jean-Baptiste Augustin',
  'Hana Song',
  'Akande Ogundimu',
  'Genji Shimada',
  'Hanzo Shimada',
  'Jamison Fawkes',
  'Lúcio Correia dos Santos',
  'Cole Cassidy',
  'Mei-Ling Zhou',
  'Fareeha Amari',
  'Gabriel Reyes',
  'Reinhardt Wilhelm',
  'Mako Rutledge',
  'Jack Morrison',
  'Olivia Colomar',
  'Satya Vaswani',
  'Torbjörn Lindholm',
  'Lena Oxton',
  'Amélie Lacroix',
  'Aleksandra Zaryanova',
  'Tekhartha Zenyatta',
  'Kiriko Shirokawa',
];
